config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'home#index'
  post '/home/update'
  get '/home/reload'
  get '/home/dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/colorpalette.rb
class Colorpalette < ApplicationRecord
  belongs_to :user
  validates_presence_of :code,:row,:column,:user_id

  # Returns an array of color code, username and time.
  # x: (Integer)row
  # y: (Integer) column
  #
  # Returns an array.
  def self.find_color_code(x, y)
    colorarray = []
    palette = Colorpalette.where(row: x, column: y).last
    colorarray = [palette.code,"#{palette.user.username} #{palette.find_time_stamp}"] if palette.present?
    colorarray
  end

  # Returns the timestamp in the format of dd-mm-yyyy hh-mm-ss.
  #
  # Returns a string.
  def find_time_stamp
    self.updated_at.strftime("%d-%m-%Y %H:%M:%S")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :colorpalettes
  validates_presence_of :username,:ipaddress

  # Generates the color code with maximum count.
  #
  # Returns a string.
  def find_fav_color
    self.colorpalettes.group(:code).count.sort {|a1,a2| a2[1]<=>a1[1]}.first[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_username

  def index
    @palettes = Colorpalette.includes(:user).all
  end

  def update
    params[:tiles].split(",").each do |tile|
      position = tile.split("-")[1].split("_")

      palette = @user.colorpalettes.find_by_row_and_column(position[0],position[1])
      if palette
        palette.update_attributes(code: params[:color_code], row: position[0],column: position[1])
      else
        @user.colorpalettes.create(code: params[:color_code], row: position[0],column: position[1])
      end
    end
    respond_to :js
  end

  def reload
    @palettes = Colorpalette.includes(:user).all
    respond_to :js
  end

  # Selects the user and palettes id counts
  #
  # Returns user object
  def dashboard
     @users = User.joins(:colorpalettes).select("users.*, count(colorpalettes.id) as count").group("users.id").order("count DESC")
  end

  private
    # Internal: Set the user if not present else create the user based on ip address
    #
    # Returns user object
    def set_username
      user = User.where(ipaddress: request.remote_ip).last
      if user.present?
        @user = user
      else
        username = "User #{User.count+1}-#{DateTime.now.to_i}"
        @user = User.create(username: username, ipaddress: request.remote_ip)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
require 'pry'
module HomeHelper

  # Generates the tiles
  # palettes: palettes containing array of colorpalettes.
  # row: (Integer) x-axis
  # column: (Integer) y-axis
  #
  # Returns the div.
  def generate_tile(palettes, row, column)
    row_palettes= palettes.group_by(&:row)
    tile_info = []
    row_palette = row_palettes[row.to_i]
    if row_palette
     column_palette = row_palette.group_by(&:column)[column.to_i]
     if column_palette
       column_palette = column_palette.last
       tile_info = [column_palette.code,"#{column_palette.user.username} #{column_palette.find_time_stamp}"]
     end
    end

    raw("<div onclick='toggleClass(this);' class='content'
       id='tile-#{row}_#{column}' #{style_attributes(tile_info)}></div>")
  end

  private

  # Internal: Returns the color code for the user
  # row: Integer
  # column: Integer
  #
  # Returns an array.
  def get_tile_details(row, column)
    Colorpalette.find_color_code(row, column)
  end

  # Internal: Returns the string containing the style and title
  # tile_info: String containing color code and user
  #
  # Returns a string
  def style_attributes(tile_info)
    "style='background-color: #{tile_info[0]}' title='#{tile_info[1]}'"
  end
end

app/views/home/_tiles.html.erb
<table>
  <%for row in 1..20 do %>
      <tr>
        <% for col in 1..20 do%>
            <td><%= generate_tile(@palettes, row, col)%></td>
        <%end%>
      </tr>
  <%end%>
</table>

app/views/home/dashboard.html.erb
<table class="leaderboard">
  <thead>
    <tr>
      <td>S.No</td>
      <td>Username</td>
      <td>Colors Placed</td>
      <td>Favorite Color</td>
    </tr>
  </thead>
  <tbody>
  <%@users.each_with_index do |user,index|%>
      <tr>
        <td><%= index+=1%>.</td>
        <td><%= user.username%></td>
        <td><%= user.count%></td>
        <td style="background-color: <%= user.find_fav_color%>"></td>
      </tr>
  <%end%>
  </tbody>
</table>

app/views/home/index.html.erb
<div id="block">
  <div id ="tiles">
    <%= render partial: "tiles"%>
  </div>
  <div class="color">
    Select color: <input class="colors">
  </div>
  <div class="button">
    <button onclick="updateTileColors();">Ok</button>
    <button>Cancel</button>
  </div>
</div>

app/views/home/reload.js.erb
$(".colors").minicolors({
  position: 'top right',
  inline: true
})
$('#tiles').html("<%= escape_javascript render(:partial => 'home/tiles',:locals => { :paletes => @palettes}) %>");

app/views/home/update.js.erb
$("div.selected").removeClass("selected");
alert("Tiles updated sucessfully");

app/views/layouts/_header.html.erb
<%= link_to "Leaderboard", home_dashboard_path%>
<%= link_to "Home Page", "/ "%>

app/views/layouts/_welcome.html.erb
<h1> Welcome <%= @user.username%></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RDA COLOR GRIDS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/welcome'%>
    <%= render partial: 'layouts/header'%>
    <%= yield %>
  </body>
</html>